### PR TITLE
feat: add gulp deploy to publish demo on gh-pages

### PR DESCRIPTION
**Pull request by hsablonniere**

### CODE REVIEW

**Comment by hsablonniere** [comment]
@mojavelinux WDYT?

**Comment by mojavelinux** [comment]
I do want to get this added. The reason I had not yet added it to the project template is because I think the way I am doing it is kind of a hack. I don't think we should be hard-coding plugin names / paths in the task. Instead, we should read the file(s) and try to determine what to include. We could merge it in the interim, but add a comment that the list of plugins may need to be updated depending on what the demo uses...but obviously that is far less ideal than it just working out of the box.

Once we are done with the main generator, we really should fold this into the [generator-bespokeplugin](https://github.com/bespokejs/generator-bespokeplugin) project. The reason I made this template project is because the plugin generator was so out of date.

**Comment by hsablonniere** [comment]
I added this : https://github.com/opendevise/bespoke-PLUGIN_NAME/blob/326f95ca112581c112f249923e7d5075351eaa8e/gulpfile.js#L81

```
// TODO list of plugins may need to be updated depending on what is needed for the demo
```

**Comment by mojavelinux** [comment]
Can you change to use 2 spaces of indent instead of 4 to be consistent with the rest of the file?

**Comment by hsablonniere** [comment]
Sorry, I forgot to change my IDE setup. This is fixed now.

**Comment by mojavelinux** [comment]
I'll merge this now. Let's plan to find a way to compile the demo in a way that does not require keeping the Gulp build task aligned with the demo HTML.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
